### ISSUE TITLE
Mouse scrolling doesn't work with new Atom version

### ISSUE THREAD

**Issue by pleonex** [refkotay/quick-scroll#1]
First, thanks for this amazing plugin!

I have recently upgrade to Atom 1.12 and I have found that when this plugin is enabled, the mouse scrolling doesn't work in the tree-view and setting panels. It was still working in the TextEditor.

After upgrading to the beta 1.13 I have seen that now the mouse scrolling doesn't work at all, even in the TextEditors.

If I disable the plugin everything starts to work again.
Let me know if you need more information about the issue.

**Comment by jolsenmultiad** [comment]
Is this issue closed now, with the 2.1.2 release of quick-scroll?

**Comment by pleonex** [comment]
Yes, after upgrading to 2.1.2 is working perfectly. Thank you so much!
