### ISSUE TITLE
Possible to always enable quick scrolling?

### ISSUE THREAD

**Issue by wrathematics** [refkotay/quick-scroll#3]
Hi, great little plugin! I'm wondering if it's possible to have it always enabled though, rather than having to press a key to use.  Maybe something like an option to reverse the current behavior (always quick, `ctrl` slows it down); but I'd settle for it just being always on.

**Comment by shelvacu** [comment]
If you want it always, just change `editor.scrollSensitivity`.

EG, in your `config.cson` file:

```
"*":
  # other stuff...
  editor:
    # other stuff...
    scrollSensitivity: 150 # add this line for super speed scrolling!
```

**Comment by wrathematics** [comment]
Awesome, thanks!
